apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otel-ochacafe-secret
  namespace: ochacafe
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: otel-ochacafe-secret
    creationPolicy: Owner
  data:
    - secretKey: otlp-traces-endpoint
      remoteRef:
        key: openobserve.trace.endpoint
    - secretKey: otlp-headers
      remoteRef:
        key: openobserve.trace.header
