apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: keycloak.admin.user
      remoteRef:
        key: user
    - secretKey: keycloak.admin.password
      remoteRef:
        key: password
