apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: keycloak.admin.user
    - secretKey: password
      remoteRef:
        key: keycloak.admin.password
    - secretKey: client_id
      remoteRef:
        key: keycloak.grafana.client_id
    - secretKey: client_secret
      remoteRef:
        key: keycloak.grafana.client_secret
