apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: rootPassword
      remoteRef:
        key: mysql.admin.password
    - secretKey: user
      remoteRef:
        key: mysql.keycloak.user
    - secretKey: password
      remoteRef:
        key: mysql.keycloak.password
