
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shukawam-cluster-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/shukawam/manifests'
    path: app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true