apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: datasource-secret
spec:
  refreshTime: 1m
  namespaceSelector:
    matchLabels:
      admin-datasource-secret: enabled
  externalSecretName: datasource-secret
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: cluster-secretstore
    target:
      name: datasource-secret
      creationPolicy: Owner
    data:
      - secretKey: url
        remoteRef:
          key: datasource.admin.url
      - secretKey: username
        remoteRef:
          key: datasource.admin.username
      - secretKey: password
        remoteRef:
          key: datasource.admin.password
