apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secretstore
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.ap-tokyo-1.cjqxrot6aahqq.abxhiljr4lp4tzwk2d7urnley6calycu44fvkbtryozqywvto3di6y3anviq
      region: ap-tokyo-1
