apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secretstore
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.ap-tokyo-1.efsf34s4aabno.abxhiljrmv3p6wslkhhauyju34ncqfslnfby2nthho7l4z5l3cuegsjhspaa
      region: ap-tokyo-1
      auth:
        user: ocid1.user.oc1..aaaaaaaakhanbd2v43dqrvuylfxdb3ftulfnxdoraw6el7pkd2hhnuo5vmdq
        tenancy: ocid1.tenancy.oc1..aaaaaaaa3mb7wrcy2ls3u3jsy2soq5ck3lc3q4mczitpdaymbuazc5tkguca
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey
            namespace: external-secret
          fingerprint:
            name: oracle-secret
            key: fingerprint
            namespace: external-secret
