apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: ghcr-secret
spec:
  refreshTime: 1m
  namespaceSelector:
    matchLabels:
      ghcr-secret: enabled
  externalSecretName: ghcr-secret
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: cluster-secretstore
    target:
      name: ghcr-secret
      template:
        type: kubernetes.io/dockerconfigjson
        engineVersion: v2
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "ghcr.io": {
                  "username":"{{ .username }}",
                  "password":"{{ .password }}",
                  "auth":"{{ .auth }}"
                }
              }
            }
      creationPolicy: Owner
    data:
      - secretKey: username
        remoteRef:
          key: ghcr.username
      - secretKey: password
        remoteRef:
          key: ghcr.password
      - secretKey: auth
        remoteRef:
          key: ghcr.auth
