apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: idcs-secret
spec:
  refreshTime: 1m
  namespaceSelector:
    matchLabels:
      idcs-secret: enabled
  externalSecretName: idcs-secret
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: cluster-secretstore
    target:
      name: idcs-secret
      creationPolicy: Owner
    data:
      - secretKey: uri
        remoteRef:
          key: idcs.uri
      - secretKey: client-id
        remoteRef:
          key: idcs.client-id
      - secretKey: client-secret
        remoteRef:
          key: idcs.client-secret
      - secretKey: frontend-uri
        remoteRef:
          key: idcs.frontend-uri
