apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: ocir-secret
spec:
  refreshTime: 1h
  namespaceSelector:
    matchLabels:
      ocir-secret: enabled
  externalSecretName: ocir-secret
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: SecretStore
      name: ocir-secret
    target:
      name: ocir-secret
      template:
        type: kubernetes.io/dockerconfigjson
      data:
        config.yaml: |
          endpoints:
            - https://{{.data.user}}:{{.data.password}}@{{.data.server}}
      creationPolicy: Owner
    data:
      - secretKey: server
        remoteRef:
          key: ocir.server
      - secretKey: user
        remoteRef:
          key: ocir.username
      - secretKey: password
        remoteRef:
          key: ocir.password
