apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: instance-capacity-monitoring
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
      app: instance-capacity-observer
  namespaceSelector:
    any: true
