apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-secret
spec:
  project: management
  source:
    repoURL: https://github.com/shukawam/manifests
    path: external-secret/namespace/datadog
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
