apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devday25-secret
spec:
  project: management
  source:
    repoURL: https://github.com/shukawam/manifests
    path: external-secret/namespace/devday25
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: devday25
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
