apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: examples-secret
spec:
  project: management
  source:
    repoURL: "https://github.com/shukawam/manifests"
    path: external-secret/namespace/examples
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: examples
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
