apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: oci
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: redis-secret
      remoteRef:
        key: shukawam-secret
