apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-password
  namespace: oci
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: redis-password
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: shukawam-secret
