env:
  konnect_mode: "on"
  cluster_mtls: pki
  cluster_control_plane: "d15b661be0.us.cp.konghq.com:443"
  cluster_server_name: "d15b661be0.us.cp.konghq.com"
  cluster_telemetry_endpoint: "d15b661be0.us.tp.konghq.com:443"
  cluster_telemetry_server_name: "d15b661be0.us.tp.konghq.com"
  cluster_dp_labels: "env:sandbox"
  cluster_cert: /etc/cert-manager/cluster/tls.crt
  cluster_cert_key: /etc/cert-manager/cluster/tls.key
  tracing_instrumentations: all
  tracing_sampling_rate: "1.0"

image:
  repository: kong/kong-ai-gateway
  tag: "2.1.0"

deployment:
  serviceAccount:
    create: true
    annotations:
      iam.gke.io/gcp-service-account: shukawam-kong-ai-gateway@gcp-fieldeng-dev.iam.gserviceaccount.com

proxy:
  type: ClusterIP
  http:
    servicePort: 8000
  tls:
    enabled: false

certificates:
  enabled: true
  duration: 87600h # 10 年 (365 * 24 * 10)
  renewBefore: 8760h # 1 年 (365 * 24)
  admin:
    enabled: false
  proxy:
    enabled: false
  cluster:
    enabled: true
    clusterIssuer: selfsigned
