apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: helidon-pod-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  podMetricsEndpoints:
    - targetPort: 8080
      path: /metrics
  namespaceSelector:
    matchNames:
      - oci-sm-app
      - monitoring
      - k8s-helidon-app
  selector:
    matchLabels:
      prometheus.io/scrape: 'true'