apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-auth
  namespace: external-secret
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.ap-tokyo-1.cjqxrot6aahqq.abxhiljr4lp4tzwk2d7urnley6calycu44fvkbtryozqywvto3di6y3anviq
      region: ap-tokyo-1
      auth:
        user: ocid1.user.oc1..aaaaaaaakhanbd2v43dqrvuylfxdb3ftulfnxdoraw6el7pkd2hhnuo5vmdq
        tenancy: ocid1.tenancy.oc1..aaaaaaaa3mb7wrcy2ls3u3jsy2soq5ck3lc3q4mczitpdaymbuazc5tkguca
        secretRef:
          privatekey:
            name: pk-fp
            key: privateKey
          fingerprint:
            name: pk-fp
            key: fingerprint