apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: 5.24.0
    chart: argo-cd
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          hosts:
            - argocd.shukawam.me
          tls:
            - hosts:
              - argocd.shukawam.me
        configs:
          cm:
            url: "https://argocd.shukawam.me/"
            application.instanceLabelKey: argocd.argoproj.io/instance
            oidc.config: |
              name: Auth0
              issuer: https://dev-l0fbo32k.jp.auth0.com/
              clientID: TNW0iqFECOsCsjBroMoTv9wyL4uDEUXr
              clientSecret: $argocd-auth0-secret:oidc.auth0.clientSecret
              requestedIDTokenClaims:
                groups:
                  essential: true
              requestedScopes:
                - openid
                - profile
                - email
                - https://argocd.shukawam.me/groups
            policy.csv: |
              g, argo-admins, role:admin
            scopes: '[https://argocd.shukawam.me/groups, email]'
  project: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
