apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
spec:
  destination:
    namespace: chaos-mesh
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://charts.chaos-mesh.org"
    targetRevision: 2.5.1
    chart: chaos-mesh
    helm:
      values: |
        chaosDaemon:
          runtime: crio
        dashboard:
          service:
            type: ClusterIP
          ingress:
            enabled: true
            certManager: false
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - name: chaosmesh.shukawam.me
                tls: true
                tlsHosts:
                - chaosmesh.shukawam.me
                tlsSecret: shukawam-tls-secret
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
