apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
spec:
  project: management
  source:
    repoURL: https://github.com/shukawam/manifests
    path: external-secret/cluster
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
