apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
spec:
  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/shukawam/manifests"
    path: cluster-autoscaler
    targetRevision: HEAD
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
