apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-at-customer-secret
spec:
  project: secret
  source:
    repoURL: "https://github.com/shukawam/manifests"
    path: external-secret/namespace/code-at-customer
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
