apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
spec:
  destination:
    namespace: projectcontour
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 10.0.0
    chart: contour
  project: contour
  syncPolicy:
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
