apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes-sigs.github.io/descheduler
    targetRevision: 0.33.0
    chart: descheduler
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
