apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
spec:
  destination:
    namespace: external-secret
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.external-secrets.io/'
    targetRevision: 0.5.7
    chart: external-secrets
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
