apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-exporter
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://falcosecurity.github.io/charts'
    targetRevision: 0.8.0
    chart: falco-exporter
    helm:
      parameters:
        - name: grafanaDashboard.namespace
          value: monitoring
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
