apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-sidekick
spec:
  project: monitoring
  source:
    repoURL: 'https://falcosecurity.github.io/charts'
    chart: falcosidekick
    targetRevision: 0.5.8
    helm:
      values: |
        webui:
          enabled: true
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - host: falcosidekick-ui.shukawam.me
                paths:
                - path: /
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true

