apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: default
  source:
    repoURL: "https://falcosecurity.github.io/charts"
    targetRevision: 1.19.4
    helm:
      parameters:
        - name: ebpf.enabled
          value: "true"
    chart: falco
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
