apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
spec:
  destination:
    namespace: falco
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://falcosecurity.github.io/charts"
    targetRevision: 3.1.5
    chart: falco
    helm:
      values: |
        driver:
          enabled: true
          kind: ebpf
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
