apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-exporter
spec:
  destination:
    namespace: falco
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://falcosecurity.github.io/charts"
    targetRevision: 0.9.5
    chart: falco-exporter
    helm:
      values: |
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
