apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
spec:
  project: monitoring
  source:
    repoURL: "https://falcosecurity.github.io/charts"
    targetRevision: 2.0.16
    chart: falco
    helm:
      values: |
        driver:
          kind: ebpf
        falco:
          grpc:
            enabled: true
          grpc_output:
            enabled: true
          json_output: true
          json_include_output_property: true
          http_output:
            enabled: true
            url: "http://falco-sidekick-falcosidekick:2801"
        certs:
          existingSecret: falco-certs
        falcosidekick:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
