apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.5.1
    chart: alloy
    helm:
      values: |
        alloy:
          listenScheme: HTTPS
          mounts:
            dockercontainers: true
            varlog: true
          securityContext:
            privileged: true
            runAsUser: 0
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - alloy.shukawam.me
          tls:
            - secretName: shukawam-tls-secret-grafana-alloy
              hosts:
                - alloy.shukawam.me
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
