apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/shukawam/manifests'
    path: influxdb
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
