apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/shukawam/manifests'
    path: ingress
    targetRevision: HEAD
  project: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
