apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    namespace: ingress-nginx
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.5.2
    chart: ingress-nginx
    helm:
      values: |
        controller:
          service:
            enabled: true
            annotations:
              oci.oraclecloud.com/load-balancer-type: "lb"
              service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
              service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
              service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "200"
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
