apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
spec:
  project: examples
  source:
    repoURL: "https://github.com/shukawam/manifests"
    path: kafka
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ochacafe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
