apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  destination:
    namespace: keycloak
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 14.0.0
    chart: keycloak
    helm:
      values: |
        tls:
          enabled: enabled
          existingSecret: shukawam-tls-secret
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: keycloak.shukawam.me
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
          tls: true
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
