apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  destination:
    namespace: identity
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 13.1.3
    chart: keycloak
    helm:
      values: |
        auth:
          adminUser: admin
          existingSecret: keycloak-secret
          passwordSecretKey: password
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: keycloak.shukawam.me
  project: identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
