apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 45.28.1
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          defaultDashboardsEnabled: false
          defaultDashboardsTimezone: jst
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.shukawam.me
            tls:
            - secretName: shukawam-tls-secret
              hosts:
              - grafana.shukawam.me
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
                - name: 'public'
                  orgId: 1
                  folder: 'public'
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/public
                - name: 'private'
                  orgId: 1
                  folder: 'private'
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/private
          dashboards:
            public:
              helidon-monitoring:
                url: https://raw.githubusercontent.com/shukawam/manifests/main/dashboards/helidon-monitoring.json
                datasource: Prometheus
            private:
              oci-logging:
                url: https://raw.githubusercontent.com/shukawam/manifests/main/dashboards/oci-logging.json
                datasource: "Oracle Cloud Infrastructure Logs"
          grafana.ini:
            server:
              root_url: https://grafana.shukawam.me
            auth.generic_oauth:
              enabled: true
              name: Keycloak
              allow_sign_up: true
              scopes: profile email groups
              client_id: grafana
              client_secret: CJc7Z5XP6HXlUXmgR7vLSDramvtaQt4L
              auth_url: https://keycloak.shukawam.me/realms/general/protocol/openid-connect/auth
              token_url: https://keycloak.shukawam.me/realms/general/protocol/openid-connect/token
              api_url: https://keycloak.shukawam.me/realms/general/protocol/openid-connect/userinfo
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
