apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    name: ""
    namespace: prometheus
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 36.2.0
    chart: kube-prometheus-stack
  project: default
