apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 54.2.2
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            remoteWrite:
              - url: https://openobserve.shukawam.me/api/default/prometheus/api/v1/write
                basicAuth:
                  username:
                    name: openobserve-secret
                    key: root_user_email
                  password:
                    name: openobserve-secret
                    key: root_user_password
        grafana:
          defaultDashboardsEnabled: true
          defaultDashboardsTimezone: jst
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.shukawam.me
            tls:
            - secretName: shukawam-tls-secret-grafana
              hosts:
              - grafana.shukawam.me
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
                - name: 'public'
                  orgId: 1
                  folder: 'public'
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/public
                - name: 'private'
                  orgId: 1
                  folder: 'private'
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/private
          grafana.ini:
            server:
              root_url: https://grafana.shukawam.me
            auth.generic_oauth:
              enabled: true
              name: Keycloak
              allow_sign_up: true
              scopes: openid profile groups email
              auth_url: https://keycloak.shukawam.me/realms/shukawam/protocol/openid-connect/auth
              token_url: https://keycloak.shukawam.me/realms/shukawam/protocol/openid-connect/token
              api_url: https://keycloak.shukawam.me/realms/shukawam/protocol/openid-connect/userinfo
              role_attribute_path: contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'guest') && 'Editor' || 'Viewer'
          env:
            name: GF_INSTALL_PLUGINS
            value: oci-logs-datasource
          envValueFrom:
            GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
              secretKeyRef:
                name: grafana-keycloak-secret
                key: client_id
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
              secretKeyRef:
                name: grafana-keycloak-secret
                key: client_secret
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
