apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langfuse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: langfuse
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://langfuse.github.io/langfuse-k8s"
    targetRevision: 0.2.2
    chart: langfuse
    helm:
      values: |
        langfuse:
          nextauth:
            url: https://langfuse.shukawam.me
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          className: nginx
          hosts:
            - host: langfuse.shukawam.me
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
              - langfuse.shukawam.me
              secretName: shukawam-tls-secret-langfuse
        postgresql:
          deploy: true
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
