apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secret
spec:
  project: secret
  source:
    repoURL: "https://github.com/shukawam/manifests"
    path: external-secret/namespace/monitoring
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
