apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
spec:
  destination:
    namespace: mysql-operator
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://mysql.github.io/mysql-operator/"
    targetRevision: 2.0.10
    chart: mysql-operator
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
