apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: neo4j
    server: https://kubernetes.default.svc
  source:
    repoURL: https://helm.neo4j.com/neo4j
    targetRevision: 4.4.35
    chart: neo4j-standslone
    helm:
      values: |
        alloy:
          configMap:
            create: false
            name: alloy-config
            key: config.alloy
          mounts:
            dockercontainers: true
            varlog: true
          securityContext:
            privileged: true
            runAsUser: 0
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
          faroPort: 12345
          hosts:
            - alloy.shukawam.me
          tls:
            - secretName: shukawam-tls-secret-grafana-alloy
              hosts:
                - alloy.shukawam.me
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
