apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ochat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: ochacafe
  source:
    repoURL: "https://github.com/shukawam/manifests"
    path: ochat
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ochacafe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
