apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-cost
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: opencost
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://opencost.github.io/opencost-helm-chart"
    targetRevision: 1.38.1
    chart: opencost
    helm:
      values: |
        opencost:
          ui:
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
                - host: opencost.shukawam.me
                  paths:
                    - /
              tls:
                - secretName: shukawam-tls-secret-opencost
                  hosts:
                    - opencost.shukawam.me
          prometheus:
            external:
              enabled: true
              url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            internal:
              enabled: false
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
