apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-instrumentation
spec:
  project: management
  source:
    repoURL: https://github.com/shukawam/manifests
    path: opentelemetry
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
