apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
spec:
  destination:
    namespace: opentelemetry
    server: https://kubernetes.default.svc
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.125.0
    chart: opentelemetry-collector
    helm:
      values: |
        mode: daemonset
        service:
          enabled: true
        image:
          repository: otel/opentelemetry-collector-k8s
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: ${env:MY_POD_IP}:4317
                  max_recv_msg_size_mib: 10
                http:
                  endpoint: ${env:MY_POD_IP}:4318
          processors:
            batch: {}
            memory_limiter:
              check_interval: 5s
              limit_percentage: 80
              spike_limit_percentage: 25
          exporters:
            debug:
              verbosity: detailed
              sampling_initial: 5
              sampling_thereafter: 200
            otlp/mackerel:
              endpoint: https://otlp-vaxila.mackerelio.com
              headers:
                Accept: */*
                Mackerel-Api-Key: ${env:MACKEREL_API_KEY}
          service:
            pipelines:
              traces:
                receivers:
                  - otlp
                processors:
                  - batch
                exporters:
                  - debug
                  - otlp/mackerel
        extraEnvsFrom:
          - secretRef:
              name: otel-collector-secret
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
