apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.115.0
    chart: opentelemetry-collector
    helm:
      values: |
        mode: deployment
        service:
          enabled: true
        image:
          repository: otel/opentelemetry-collector-k8s
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: ${env:MY_POD_IP}:4317
                  max_recv_msg_size_mib: 10
                http:
                  endpoint: ${env:MY_POD_IP}:4318
          processors:
            batch: {}
            memory_limiter:
              check_interval: 5s
              limit_percentage: 80
              spike_limit_percentage: 25
          exporters:
            otlphttp/oci:
              endpoint: https://aaaaddtuwwwg6aaaaaaaaacsxy.apm-agt.ap-tokyo-1.oci.oraclecloud.com/20200101/opentelemetry/private
              headers:
                Authorization: ${env:OCI_APM_DATAKEY}
            debug:
              verbosity: detailed
              sampling_initial: 5
              sampling_thereafter: 200
          service:
            pipelines:
              traces:
                receivers:
                  - otlp
                processors:
                  - batch
                exporters:
                  - otlphttp/oci
                  - debug
        extraEnvsFrom:
          - secretRef:
              name: otel-collector-secret
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
