apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 36.2.0
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            hosts:
              - grafana.shukawam.com
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
                - name: 'default'
                  orgId: 1
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default
                - name: 'public'
                  orgId: 1
                  folder: 'public'
                  type: file
                  disableDetetion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/public
                - name: 'private'
                  orgId: 1
                  folder: 'private'
                  type: file
                  disableDetetion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/private
          dashboards:
            public:
              prometheus-stats:
                gnetId: 14584
            private:
              falco:
                gnetId: 11914
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
