apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 36.2.0
    chart: kube-prometheus-stack
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
