apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-ingress
spec:
  project: default
  source:
    repoURL: "https://github.com/shukawam/manifests"
    path: prometheus/ingress.yaml
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
