apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.3.0
    chart: pyroscope
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - pyroscope.shukawam.me
          rules:
            - host: pyroscope.shukawam.me
              paths:
                path: /
                pathType: Prefix
          tls:
            - secretName: shukawam-tls-secret-pyroscope
              hosts:
                - pyroscope.shukawam.me
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
