apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rolldice
spec:
  project: management
  source:
    repoURL: "https://github.com/oracle-japan/ochacafe-opentelemetry"
    path: rolldice-zero-code/k8s
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
