apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-monitor
spec:
  project: management
  source:
    repoURL: "https://github.com/shukawam/manifests"
    path: service-monitor
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
