apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-plugin-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: grafana-plugin-secret
    creationPolicy: Owner
  data:
    - secretKey: plugins
      remoteRef:
        key: grafana.plugins
