apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-auth0-secret
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: grafana-auth0-secret
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: auth0.grafana.client_id
    - secretKey: client_secret
      remoteRef:
        key: auth0.grafana.client_secret
