apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: mysql.innodb.username
    - secretKey: password
      remoteRef:
        key: mysql.innodb.password
