apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openobserve-secret
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: openobserve-secret
    creationPolicy: Owner
  data:
    - secretKey: root_user_email
      remoteRef:
        key: openobserve.root_user_email
    - secretKey: root_user_password
      remoteRef:
        key: openobserve.root_user_password
