apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-secret
  namespace: datadog
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: datadog-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: datadog
  data:
    - secretKey: api-key
      remoteRef:
        key: datadog.apikey
