{
 "title": "GPU Instance Capacity Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TGjA:AP-TOKYO-1-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:AP-TOKYO-1-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:AP-OSAKA-1-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:AP-OSAKA-1-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:AP-SEOUL-1-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:AP-SEOUL-1-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:AP-SYDNEY-1-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:AP-SYDNEY-1-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:EU-FRANKFURT-1-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:EU-FRANKFURT-1-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:EU-FRANKFURT-1-AD-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:EU-FRANKFURT-1-AD-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:EU-FRANKFURT-1-AD-3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:EU-FRANKFURT-1-AD-3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:PHX-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:PHX-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:PHX-AD-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:PHX-AD-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:PHX-AD-3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:PHX-AD-3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:UK-LONDON-1-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:UK-LONDON-1-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:UK-LONDON-1-AD-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:UK-LONDON-1-AD-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:UK-LONDON-1-AD-3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:UK-LONDON-1-AD-3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:US-ASHBURN-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:US-ASHBURN-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:US-ASHBURN-AD-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:US-ASHBURN-AD-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:US-ASHBURN-AD-3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:US-ASHBURN-AD-3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:US-CHICAGO-1-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:US-CHICAGO-1-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:US-CHICAGO-1-AD-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:US-CHICAGO-1-AD-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:US-CHICAGO-1-AD-3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:US-CHICAGO-1-AD-3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:US-SANJOSE-1-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:US-SANJOSE-1-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TGjA:CA-TORONTO-1-AD-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "gpu_shape_status{availability_domain=\"TGjA:CA-TORONTO-1-AD-1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}