apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak
  namespace: identity
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: keycloak
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: keycloak.password
