apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ochat-secret
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: ochat-secret
    creationPolicy: Owner
  data:
    - secretKey: COHERE_API_KEY
      remoteRef:
        key: ochat.cohere_api_key
    - secretKey: LANGFUSE_SECRET_KEY
      remoteRef:
        key: ochat.langfuse_secret_key
    - secretKey: LANGFUSE_PUBLIC_KEY
      remoteRef:
        key: ochat.langfuse_public_key
    - secretKey: LANGFUSE_HOST
      remoteRef:
        key: ochat.langfuse_host
    - secretKey: MILVUS_URI
      remoteRef:
        key: ochat.milvus_uri
    - secretKey: COLLECTION_NAME
      remoteRef:
        key: ochat.collection_name
