apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
  namespace: kong
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  gatewayClassName: kong
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.gke.shukawam.me"
      tls:
        mode: Terminate
        certificateRefs:
          # 既定値だが、省略すると API サーバが埋めた値と git に差分が出る
          - group: ""
            kind: Secret
            name: gke-shukawam-me-tls
      allowedRoutes:
        namespaces:
          from: All
