apiVersion: v1
kind: Service
metadata:
  name: headroom
  namespace: kong
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: headroom
  ports:
    - name: http
      port: 8787
      targetPort: http
