server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argocd.shukawam.me
    tls:
      - secretName: shukawam-tls-secret-argocd
        hosts:
          - argocd.shukawam.me
configs:
  cm:
    url: https://argocd.shukawam.me
    oidc.config: |
      name: keycloak
      issuer: https://keycloak.shukawam.me/realms/shukawam
      clientID: ffa050ff-85c2-478a-9e44-d54c2a06b870
      clientSecret: $argocd.keycloak.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
