server:
  metrics:
    enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argocd.shukawam.me
    tls:
      - secretName: shukawam-tls-secret-argocd
        hosts:
          - argocd.shukawam.me
configs:
  cm:
    url: https://argocd.shukawam.me
    admin.enabled: false
    oidc.config: |
      name: keycloak
      issuer: https://keycloak.shukawam.me/realms/shukawam
      clientID: argocd
      clientSecret: $argocd.keycloak.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
    secret:
      createSecret: false
controller:
  metrics:
    enabled: true
dex:
  metrics:
    enabled: true
redis:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
