global:
  domain: argocd.shukawam.me
server:
  metrics:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx
    tls: true
    extraTls:
      - secretName: shukawam-tls-secret-argocd
        hosts:
          - argocd.shukawam.me
configs:
  cm:
    url: https://argocd.shukawam.me
    admin.enabled: false
    oidc.config: |
      name: Auth0
      issuer: https://dev-l0fbo32k.jp.auth0.com/
      clientID: $argocd.auth0.clientId
      clientSecret: $argocd.auth0.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
    secret:
      createSecret: false
  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, get, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, logs, get, *, allow
      p, role:admin, exec, create, */*, allow
      g, argocd-admins, role:admin
    scopes: "[https://shukawam.me/groups]"
controller:
  metrics:
    enabled: true
dex:
  metrics:
    enabled: true
redis:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
