apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: shukawam-cluster
    site: ap1.datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    admissionController:
      enabled: true
      mutateUnlabelled: false
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        hostPort: 8126 # default
