apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: opentelemetry
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    # Terraform の otel_collector_ksa_annotation 出力と一致させること
    iam.gke.io/gcp-service-account: shukawam-otel-collector@gcp-fieldeng-dev.iam.gserviceaccount.com
