apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-redis-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: http-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
  namespaceSelector:
    any: true
