apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otel-collector-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: otel-collector-secret
    creationPolicy: Owner
  data:
    - secretKey: OCI_APM_DATAKEY
      remoteRef:
        key: oci.apm.datakey
    - secretKey: MACKEREL_ENDPOINT
      remoteRef:
        key: mackerel.endpoint
    - secretKey: MACKEREL_API_KEY
      remoteRef:
        key: mackerel.apikey
