apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
    - secretKey: oidc.auth0.clientSecret
      remoteRef:
        key: auth0.clientSecret
