apiVersion: apps/v1
kind: Deployment
metadata:
  name: ochat
  namespace: ochacafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ochat
  template:
    metadata:
      labels:
        app: ochat
    spec:
      initContainers:
        - image: ghcr.io/oracle/oci-cli:latest
          name: download-wallet
          volumeMounts:
            - mountPath: /var/cache
              name: cache-volume
          env:
            - name: ADB_OCID
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: ADB_OCID
            - name: WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: WALLET_PASSWORD
                  name: ochat-secret
          command: ["/bin/bash"]
          args:
            - -c
            - >-
              mkdir -p /var/cache/wallet &&
              oci --auth instance_principal
              --region ap-tokyo-1
              db autonomous-database generate-wallet
              --autonomous-database-id $(ADB_OCID)
              --password $WALLET_PASSWORD
              --file /var/cache/wallet/wallet.zip &&
              echo "Wallet password is saved in /var/cache/wallet/password"
        - image: busybox:latest
          name: unzip-wallet
          volumeMounts:
            - mountPath: /var/cache
              name: cache-volume
          command:
            ["unzip", "-d", "/var/cache/wallet", "/var/cache/wallet/wallet.zip"]
      containers:
        - name: ochat
          image: nrt.ocir.io/orasejapan/shukawam/ochat:0.1.2
          ports:
            - name: api
              containerPort: 8501
          env:
            - name: LANGFUSE_RELEASE
              value: 0.1.1
            - name: COMPARTMENT_ID
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: COMPARTMENT_ID
            - name: GENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: GENAI_ENDPOINT
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: LANGFUSE_SECRET_KEY
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: LANGFUSE_PUBLIC_KEY
            - name: LANGFUSE_HOST
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: LANGFUSE_HOST
            - name: MILVUS_URI
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: MILVUS_URI
            - name: COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: COLLECTION_NAME
            - name: ORACLE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: ORACLE_USERNAME
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: ORACLE_PASSWORD
            - name: ORACLE_DSN
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: ORACLE_DSN
            - name: WALLET_DIR
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: WALLET_DIR
            - name: WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: WALLET_PASSWORD
            - name: TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: TABLE_NAME
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache
      imagePullSecrets:
        - name: ocir-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
