apiVersion: apps/v1
kind: Deployment
metadata:
  name: ochat
  namespace: ochacafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ochat
  template:
    metadata:
      labels:
        app: ochat
    spec:
      containers:
        - name: ochat
          image: nrt.ocir.io/orasejapan/shukawam/ochat:0.0.5
          ports:
            - name: api
              containerPort: 8501
          env:
            - name: COMPARTMENT_ID
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: COMPARTMENT_ID
            - name: GENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: GENAI_ENDPOINT
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: LANGFUSE_SECRET_KEY
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: LANGFUSE_PUBLIC_KEY
            - name: LANGFUSE_HOST
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: LANGFUSE_HOST
            - name: MILVUS_URI
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: MILVUS_URI
            - name: COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: ochat-secret
                  key: COLLECTION_NAME
      imagePullSecrets:
        - name: ocir-secret
