apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ochat
  namespace: ochacafe
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ochat.shukawam.me
      secretName: shukawam-tls-secret-ochat
  rules:
    - host: ochat.shukawam.me
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ochat-service
                port:
                  number: 8501
