apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://charts.konghq.com
      chart: kong-operator
      targetRevision: 1.4.0-rc.1
      helm:
        valueFiles:
          - $values/platform/kong-operator/values.yaml
    - repoURL: https://github.com/shukawam/manifests.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      # CRD を誤って消さないため、このアプリだけ prune しない
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
