apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-ai-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://charts.konghq.com
      chart: kong-ai-gateway
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/platform/kong-ai-gateway/values.yaml
    - repoURL: https://github.com/shukawam/manifests.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
