apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: ochacafe
  labels:
    strimzi.io/cluster: ochacafe
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic ochacafe using consumer group ochacafe-group
      - resource:
          type: topic
          name: ochacafe
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name: ochacafe-group
          patternType: literal
        operations:
          - Read
        host: "*"
      # Example Producer Acls for topic ochacafe
      - resource:
          type: topic
          name: ochacafe
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
