apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ochacafe-event
  labels:
    strimzi.io/cluster: ochacafe
spec:
  # 省略した場合は、クラスタのdefault設定から引き継がれる
  # partitions: 3
  # replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
