apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: ochacafe
  labels:
    strimzi.io/cluster: ochacafe
spec:
  replicas: 1
  bootstrapServers: ochacafe-kafka-bootstrap:9092
  http:
    port: 8080
  enableMetrics: true
