apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helidon
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
  selector:
    matchLabels:
      prometheus.io/scrape: 'true'