kind: Deployment
apiVersion: apps/v1
metadata:
  name: gpu-capacity-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-capacity-exporter
  template:
    metadata:
      labels:
        app: gpu-capacity-exporter
        version: v1
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: gpu-capacity-exporter
          image: nrt.ocir.io/orasejapan/shukawam/gpu-capacity-exporter:1.0.3
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: gpu-capacity-exporter
          readinessProbe:
            httpGet:
              path: /health/ready
              port: api
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: api
            initialDelaySeconds: 30
            periodSeconds: 5
      imagePullSecrets:
        - name: ocir-secret
