kind: Service
apiVersion: v1
metadata:
  name: gpu-capacity-exporter
  labels:
    app: gpu-capacity-exporter
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: gpu-capacity-exporter
  ports:
  - port: 8080
    targetPort: 8080
    name: http
