apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devday-secret
  namespace: examples
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: devday-secret
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: devday.google_api_key
    - secretKey: USERNAME
      remoteRef:
        key: devday.username
    - secretKey: PASSWORD
      remoteRef:
        key: devday.password
    - secretKey: DSN
      remoteRef:
        key: devday.dsn
    - secretKey: COMPARTMENT_ID
      remoteRef:
        key: devday.compartment_id
    - secretKey: TRACELOOP_API_KEY
      remoteRef:
        key: devday.traceloop_api_key
    - secretKey: DD_API_KEY
      remoteRef:
        key: datadog.apikey
