apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-rp-secret
  namespace: examples
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: oidc-rp-secret
    creationPolicy: Owner
  data:
    - secretKey: keycloak_uri
      remoteRef:
        key: keycloak.ochacafe.uri
    - secretKey: keycloak_client_id
      remoteRef:
        key: keycloak.ochacafe.client_id
    - secretKey: keycloak_client_secret
      remoteRef:
        key: keycloak.ochacafe.client_secret
    - secretKey: keycloak_frontend_uri
      remoteRef:
        key: keycloak.ochacafe.frontend_uri
    - secretKey: api_endpoint_base
      remoteRef:
        key: keycloak.ochacafe.api_endpoint_base
